version: "3.9"
services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - $PORT:3000
    depends_on:
      db:
        condition: service_healthy
    
  db:
    container_name: db
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    environment:
      - PGDATA=/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - database:/data/postgres

volumes:
  database: